name: tigr81 CI CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.8']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependency
      working-directory: ./tigr81
      run: poetry install --with test

    - name: Run tests
      working-directory: ./tigr81
      run: poetry run pytest
     
  publish:
    needs: [test]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Poetry
        run: pip install poetry

      - name: Config pypi
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry config pypi-token.pypi $PYPI_API_TOKEN

      - name: Publishing package
        working-directory: ./tigr81
        run: poetry publish --build